'use client';
import {useState} from 'react';
import {Search,Trash2,Pencil} from 'lucide-react';
type Props={kind:'clients'|'schemes';rows:any[];onSave:(payload:any)=>Promise<void>};
export function MasterManager({kind,rows,onSave}:Props){
 const [query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState<any>(null),[form,setForm]=useState<any>({}),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const filtered=rows.filter(r=>query.toLowerCase().trim().split(/\s+/).every(q=>[r.id,r.name,r.official,r.amc,r.category].filter(Boolean).join(' ').toLowerCase().includes(q)));
 const pages=Math.max(1,Math.ceil(filtered.length/50)),current=Math.min(page,pages-1),visible=filtered.slice(current*50,current*50+50);
 const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 async function save(payload:any){setBusy(true);setError('');try{await onSave(payload);setSelected(new Set());setEditing(null);setConfirm(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="mastermanager" aria-label={kind+' management'}>
 <div className="searchfield"><Search size={18}/><input aria-label={'Search '+kind} placeholder={kind==='clients'?'Search client name or Iwell ID…':'Search scheme, ID, AMC or category…'} value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div>
 <div className="mastertoolbar"><span>{filtered.length.toLocaleString('en-IN')} of {rows.length.toLocaleString('en-IN')} {kind} · {selected.size} selected</span><button className="secondary" disabled={!selected.size||busy} onClick={()=>{setConfirm(true);setEditing(null);setError('')}}><Trash2 size={16}/>Delete selected</button>{selected.size>0&&<button className="secondary" disabled={busy} onClick={()=>setSelected(new Set())}>Clear selection</button>}</div>
 {error&&<p className="red" role="alert">{error}</p>}
 {confirm&&<div className="mastereditor" role="alert"><h3>Delete {selected.size} {kind}?</h3><p>These records will be removed from the master list and current selection. Saved allocations will keep their original details. {kind==='schemes'&&'Baskets containing deleted schemes will need replacement schemes.'}</p><div className="mastertoolbar"><button className="primary" disabled={busy} onClick={()=>save({action:'deleteMaster',kind,ids:[...selected]})}>{busy?'Deleting…':'Confirm deletion'}</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div></div>}
 {editing&&<form className="mastereditor" onSubmit={e=>{e.preventDefault();save({action:'editMaster',kind,id:editing.id,record:form})}}><h3>Edit {kind==='clients'?'client':'scheme'}</h3><div className="masterfields">{(kind==='clients'?[['id','Iwell ID'],['name','Client name']]:[['id','Scheme ID'],['name','Display name'],['official','Official scheme name'],['amc','AMC'],['category','Category'],['plan','Plan'],['option','Option']]).map(([key,label])=><label key={key}>{label}<input required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{kind==='schemes'&&<label>Status<select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Inactive</option></select></label>}</div><div className="mastertoolbar"><button className="primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 <div className="mastertable"><table><thead><tr><th><input type="checkbox" aria-label="Select all records on this page" disabled={busy||!visible.length} checked={visible.length>0&&visible.every(r=>selected.has(r.id))} onChange={e=>{const checked=e.target.checked;setSelected(s=>{const n=new Set(s);visible.forEach(r=>checked?n.add(r.id):n.delete(r.id));return n})}}/></th><th>{kind==='clients'?'Iwell ID':'Scheme ID'}</th><th>{kind==='clients'?'Client name':'Scheme details'}</th><th>Action</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={'Select '+r.name} checked={selected.has(r.id)} disabled={busy} onChange={()=>toggle(r.id)}/></td><td>{r.id}</td><td><b>{r.name}</b>{kind==='schemes'&&<small>{r.amc} · {r.category} · {r.active?'Active':'Inactive'}</small>}</td><td><button className="secondary" disabled={busy} onClick={()=>{setEditing(r);setForm({...r});setConfirm(false);setError('')}}><Pencil size={14}/>Edit</button></td></tr>)}</tbody></table>{!visible.length&&<p className="hint">No matching {kind}.</p>}</div>
 <div className="mastertoolbar"><button className="secondary" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {pages} · 50 per page</span><button className="secondary" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div>
 </section>
}
