'use client';
import {useState} from 'react';
import type {Client,Scheme} from '@/lib/domain';
import {money} from '@/lib/domain';
import type {Holding,Portfolio} from '@/lib/portfolio';
import {validateHoldings} from '@/lib/portfolio';
export function PortfolioManager({client,portfolio,schemes,onSave,onAdd}:{client:Client;portfolio?:Portfolio;schemes:Scheme[];onSave:(p:Portfolio)=>Promise<void>;onAdd:(s:Scheme,folio:string)=>void}){
 const [draft,setDraft]=useState<Portfolio|undefined>(portfolio),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<Holding|null>(null),[verified,setVerified]=useState(false),[imported,setImported]=useState(false),[deleteId,setDeleteId]=useState(''),[replaceFile,setReplaceFile]=useState<File|null>(null),[schemeQuery,setSchemeQuery]=useState('');
 const rows=draft?.holdings||[];const needsReview=rows.filter(h=>!h.schemeId||!h.amc.trim());const results=rows.filter(h=>(h.name+' '+h.amc+' '+h.folio).toLowerCase().includes(query.toLowerCase()));
 async function read(file:File){setBusy(true);setError('');setStatus('');try{const {readPortfolio}=await import('@/lib/read-portfolio');const r=await readPortfolio(file,schemes);setDraft({id:crypto.randomUUID(),clientId:client.id,clientName:r.clientName,source:r.source,asOf:r.asOf,holdings:r.holdings,originalHoldings:structuredClone(r.holdings),reportedValue:r.reportedValue,importedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setImported(true);setVerified(false);setDirty(true);setEdit(null);setStatus('Read '+r.holdings.length+' holdings. Check the report owner, folios and scheme matches before saving.')}catch(e){setError((e as Error).message)}finally{setBusy(false);setReplaceFile(null)}}
 function change(h:Holding){const next=rows.some(x=>x.id===h.id)?rows.map(x=>x.id===h.id?h:x):[...rows,h];try{validateHoldings(next);setDraft(d=>({...d!,holdings:next}));setDirty(true);setEdit(null);setError('')}catch(e){setError((e as Error).message)}}
 async function save(){if(!draft)return;setBusy(true);setError('');try{validateHoldings(rows);await onSave({...draft,updatedAt:new Date().toISOString()});setDirty(false);setImported(false);setStatus('Portfolio saved for '+client.name+'.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const field=(key:'units'|'nav'|'invested'|'value',label:string)=> <label>{label}<input type="number" min="0" step={key==='units'||key==='nav'?'0.0001':'0.01'} required value={edit![key]/(key==='invested'||key==='value'?100:1)} onChange={e=>setEdit({...edit!,[key]:key==='invested'||key==='value'?Math.round(Number(e.target.value)*100):Number(e.target.value)})}/></label>;
 return <section className="portfoliomanager"><div className="portfolioowner"><b>{client.name}</b><span>{client.id}</span></div><p className="hint">Import a single-client Wealth Elite or Investwell PDF. Review and save it to this client. Re-import replaces the current snapshot; it does not add the same holdings twice. Changes here update your local records, not AMC transactions.</p>
 <div className="mastertoolbar"><label className="secondary">{busy?'Reading…':'Import portfolio PDF'}<input className="sr-only" disabled={busy} type="file" accept=".pdf,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f){if(rows.length||dirty)setReplaceFile(f);else read(f)}e.target.value=''}}/></label><button className="secondary" disabled={busy} onClick={()=>{if(!draft)setDraft({id:crypto.randomUUID(),clientId:client.id,clientName:client.name,source:'Manual',asOf:new Date().toISOString().slice(0,10),holdings:[],originalHoldings:[],importedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setEdit({id:crypto.randomUUID(),name:'',schemeId:'',amc:'',folio:'',units:0,nav:0,invested:0,value:0});setSchemeQuery('')}}>Add holding manually</button><button className="primary" disabled={!dirty||busy||(imported&&!verified)} onClick={save}>Save portfolio{dirty?' changes':''}</button></div>
 {replaceFile&&<div className="mastereditor"><p>Replace the current portfolio preview with {replaceFile.name}? Unsaved edits will be discarded. The saved portfolio changes only after you review and save.</p><button className="primary" disabled={busy} onClick={()=>read(replaceFile)}>Read replacement</button> <button className="secondary" disabled={busy} onClick={()=>setReplaceFile(null)}>Cancel</button></div>}
 {error&&<p className="red" role="alert">{error}</p>}{status&&<p className="hint" role="status">{status}</p>}
 {draft&&<><div className="portfoliostats"><span><small>Report</small>{draft.source} · {draft.asOf||'Date not supplied'}</span><span><small>Current value</small>{money(rows.reduce((n,h)=>n+h.value,0))}</span><span><small>Invested</small>{money(rows.reduce((n,h)=>n+h.invested,0))}</span><span><small>Holdings</small>{rows.length}</span></div>{imported&&<label className="reviewcheck"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span>I checked that the report for <b>{draft.clientName||'an unidentified owner'}</b> belongs to <b>{client.name} ({client.id})</b>, and reviewed the extracted holdings and folios.</span></label>}
 {dirty&&<p className="hint">Unsaved changes. Save before adding holdings to the allocation cart. Original imported values are retained separately when you edit this snapshot.</p>}
 {edit&&<form className="mastereditor" onSubmit={e=>{e.preventDefault();change(edit)}}><h3>Edit holding</h3><label>Find a scheme in the master<input placeholder="Search scheme name…" value={schemeQuery} onChange={e=>setSchemeQuery(e.target.value)}/></label><label>Linked scheme<select value={edit.schemeId} onChange={e=>{const s=schemes.find(x=>x.id===e.target.value);setEdit({...edit,schemeId:s?.id||'',...(s?{name:s.name,amc:s.amc}:{})})}}><option value="">Unmatched — keep report name</option>{schemes.filter(s=>s.id===edit.schemeId||(schemeQuery&&s.name.toLowerCase().includes(schemeQuery.toLowerCase()))).slice(0,100).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="masterfields"><label>Scheme name<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value,schemeId:''})}/></label><label>AMC<input required list="portfolio-amcs" value={edit.amc} onChange={e=>setEdit({...edit,amc:e.target.value,schemeId:''})}/><datalist id="portfolio-amcs">{[...new Set(schemes.map(s=>s.amc))].map(a=><option key={a}>{a}</option>)}</datalist></label><label>Folio number<input required value={edit.folio} onChange={e=>setEdit({...edit,folio:e.target.value})}/></label>{field('units','Units')}{field('nav','NAV')}{field('invested','Invested amount (INR)')}{field('value','Current value (INR)')}</div><p className="hint">Values are entered independently. Editing units or NAV does not recalculate the reported current value.</p><button className="primary">Apply holding changes</button> <button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancel</button></form>}
 {needsReview.length>0&&<div className="portfolioreview"><span><b>{needsReview.length} holding{needsReview.length===1?'':'s'} need review</b><small>They are saved in the portfolio, but must be matched to the scheme master before adding a new investment.</small></span><button className="secondary" onClick={()=>setQuery('')}>Show in list</button></div>}
 <div className="searchfield"><input aria-label="Search portfolio" placeholder="Search holdings, AMC or folio…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {deleteId&&<div className="mastereditor"><p>Remove this holding from the current snapshot? It remains in the original imported data.</p><button className="primary" onClick={()=>{setDraft({...draft,holdings:rows.filter(h=>h.id!==deleteId)});setDirty(true);setDeleteId('')}}>Remove holding</button> <button className="secondary" onClick={()=>setDeleteId('')}>Cancel</button></div>}
 <div className="portfoliotable"><table><thead><tr><th>Scheme / folio</th><th>Units</th><th>Current value</th><th>Actions</th></tr></thead><tbody>{results.map(h=><tr key={h.id} className={!h.schemeId||!h.amc.trim()?'needsreview':''}><td><b>{h.name}</b><small>{h.amc||'AMC not identified'} · Folio {h.folio}</small>{!h.schemeId&&<small className="red">Match to a master scheme before adding an investment</small>}</td><td>{h.units.toLocaleString('en-IN',{maximumFractionDigits:4})}</td><td>{money(h.value)}</td><td><div className="holdingactions"><button className="secondary" onClick={()=>{setEdit({...h});setSchemeQuery('')}}>Edit / match</button><button className="secondary" disabled={dirty||!h.schemeId||!schemes.some(s=>s.id===h.schemeId&&s.active)} onClick={()=>{const s=schemes.find(s=>s.id===h.schemeId)!;onAdd(s,h.folio);setStatus(h.name+' added for a new investment using folio '+h.folio)}}>Add investment</button><button className="secondary" onClick={()=>setDeleteId(h.id)}>Remove</button></div></td></tr>)}</tbody></table></div>
 {draft.originalHoldings.length>0&&<details><summary>Original imported snapshot ({draft.originalHoldings.length} holdings)</summary><div className="portfoliotable"><table><thead><tr><th>Scheme</th><th>Folio</th><th>Units</th><th>Current value</th></tr></thead><tbody>{draft.originalHoldings.map(h=><tr key={h.id}><td>{h.name}</td><td>{h.folio}</td><td>{h.units}</td><td>{money(h.value)}</td></tr>)}</tbody></table></div></details>}</>}
 </section>
}
