export type Client={id:string;name:string};
export type Scheme={id:string;official:string;name:string;amc:string;category:string;plan:string;option:string;active:boolean};
export type Line={scheme:Scheme;amount:number};
export type Allocation={id:string;client:Client;total:number;lines:Line[];status:'draft'|'final';date:string;queued?:boolean};
export type Basket={id:string;name:string;items:{id:string;pct:number}[]};
export const categories=['Flexi Cap','Large Cap','Large & Mid Cap','Mid Cap','Small Cap','Multi Cap','Focused','Value / Contra','ELSS','Multi Asset','Balanced Advantage','Aggressive Hybrid','Conservative Hybrid','Equity Savings','Arbitrage','Liquid','Money Market','Ultra Short Duration','Low Duration','Short Duration','Corporate Bond','Banking & PSU','Gilt','Gold','Silver','International','Index Funds','ETFs','SIF'];
export const sampleClients:Client[]=[{id:'IW1001',name:'Aarav Shah'},{id:'IW1002',name:'Priya Mehta'},{id:'IW1003',name:'Rohan Desai'},{id:'IW1004',name:'Ananya Patel'},{id:'IW1005',name:'Vikram Purohit'}];
const rows=[['Kotak','Kotak Flexicap Fund','Flexi Cap'],['HDFC','HDFC Flexi Cap Fund','Flexi Cap'],['ICICI Prudential','ICICI Prudential Flexicap Fund','Flexi Cap'],['Parag Parikh','Parag Parikh Flexi Cap Fund','Flexi Cap'],['SBI','SBI Flexicap Fund','Flexi Cap'],['Nippon India','Nippon India Multi Cap Fund','Multi Cap'],['HDFC','HDFC Mid Cap Fund','Mid Cap'],['ICICI Prudential','ICICI Prudential Multi Asset Fund','Multi Asset'],['SBI','SBI Balanced Advantage Fund','Balanced Advantage'],['Nippon India','Nippon India Small Cap Fund','Small Cap'],['Axis','Axis Small Cap Fund','Small Cap'],['Kotak','Kotak Midcap Fund','Mid Cap'],['Mirae Asset','Mirae Asset Large & Midcap Fund','Large & Mid Cap'],['HDFC','HDFC Large Cap Fund','Large Cap'],['DSP','DSP Value Fund','Value / Contra'],['Aditya Birla Sun Life','Aditya Birla Sun Life ELSS Tax Saver Fund','ELSS'],['UTI','UTI Nifty 50 Index Fund','Index Funds'],['Tata','Tata Liquid Fund','Liquid'],['Motilal Oswal','Motilal Oswal Midcap Fund','Mid Cap'],['Franklin Templeton','Franklin India Flexi Cap Fund','Flexi Cap'],['Invesco','Invesco India Contra Fund','Value / Contra'],['Bandhan','Bandhan Small Cap Fund','Small Cap'],['Canara Robeco','Canara Robeco Large Cap Fund','Large Cap'],['HDFC','HDFC Corporate Bond Fund','Corporate Bond'],['SBI','SBI Gold Fund','Gold'],['ICICI Prudential','ICICI Prudential Silver ETF','Silver'],['Kotak','Kotak Equity Arbitrage Fund','Arbitrage'],['Axis','Axis Banking & PSU Debt Fund','Banking & PSU'],['HDFC','HDFC Gilt Fund','Gilt'],['Tata','Tata Money Market Fund','Money Market']];
export const sampleSchemes:Scheme[]=rows.map(([amc,name,category],i)=>({id:`S${String(i+1).padStart(3,'0')}`,name,official:`${name} - Regular Plan - Growth`,amc:`${amc} Mutual Fund`,category,plan:'Regular',option:'Growth',active:true}));
export const sampleBaskets:Basket[]=[{id:'balanced',name:'Balanced Allocation',items:[{id:'S001',pct:40},{id:'S007',pct:25},{id:'S008',pct:20},{id:'S009',pct:15}]},{id:'growth',name:'Growth Allocation',items:[{id:'S004',pct:50},{id:'S007',pct:30},{id:'S010',pct:20}]}];
export const money=(n:number)=>'₹'+(n/100).toLocaleString('en-IN',{minimumFractionDigits:n%100?2:0,maximumFractionDigits:2});
export function parseMoney(v:string){const n=Number(v.replace(/[,₹\s]/g,''));return Number.isFinite(n)&&n>=0&&n<=1e10?Math.round(n*100):0}
export function splitAmount(total:number,weights:number[]){const sum=weights.reduce((a,b)=>a+b,0);if(!sum)return weights.map(()=>0);const out=weights.map(w=>Math.floor(total*w/sum));let rest=total-out.reduce((a,b)=>a+b,0);for(let i=0;rest>0;i++,rest--)out[i%out.length]++;return out}
export function matches(s:string,q:string){const n=s.toLowerCase().replace(/[^a-z0-9]/g,'');return q.toLowerCase().split(/\s+/).filter(Boolean).every(t=>n.includes(t.replace(/[^a-z0-9]/g,'')))}
export function validateAllocation(a:Allocation,final=false){if(!a.client?.id)throw Error('Select a client first.');if(!Number.isSafeInteger(a.total)||a.total<=0||a.total>1e12)throw Error('Enter a valid investment amount.');if(!a.lines.length)throw Error('Add at least one scheme.');if(new Set(a.lines.map(l=>l.scheme.id)).size!==a.lines.length)throw Error('Duplicate schemes are not allowed.');if(a.lines.some(l=>!Number.isSafeInteger(l.amount)||l.amount<0))throw Error('Amounts must be valid and non-negative.');if(final&&(a.lines.some(l=>l.amount<=0)||a.lines.reduce((s,l)=>s+l.amount,0)!==a.total))throw Error('Allocate the full investment with a positive amount for every scheme.');}
